version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.54
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: curl -L https://github.com/bep/s3deploy/releases/download/v2.0.1/s3deploy_2.0.1_Linux-64bit.tar.gz | tar xvz
      - run: hugo --buildFuture --buildDrafts --buildExpireda
      - run: ls public
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ./s3deploy -region=us-east-1 -bucket=ccisweb-bolabx-use1 
            else
              echo "Not master branch, dry run only"
            fi
